"""Payments

Revision ID: 63818507f674
Revises: 20a3b50ded5c
Create Date: 2020-04-26 18:44:31.646900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63818507f674'
down_revision = '20a3b50ded5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_payment',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('amount_paid', sa.Integer(), nullable=True),
    sa.Column('client_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('lead_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('funnel_step_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['funnel_step_id'], ['funnel_steps.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_payment')
    # ### end Alembic commands ###
